language: rust
rust:
  - nightly

env:
  global:
    secure: "CcdV2J4ElRioFt4bjlgo3YY4mj8HTFv+t4lrpWIwisCCjxlZEQUsNpM820AmkLA4Q4C21GKKgpiw/Ef+S7WznuUJlMBobBFGPB+rr+xORFCyaNm9nyfJ+zLPuNBe9E+/X5CWkDtXzzNistxLDCnvrUOVOR4uQF5cxI0PB4VUqs8="

script:
  - cargo test
