[package]
name = "beehave"
version = "0.0.1"
authors = ["Ryan Scott <atthealma@gmail.com>"]

[[bin]]

name = "example"
path = "example/main.rs"
bench = true
test = false
doctest = false
doc = false

[lib]

name = "beehave"
path = "src/lib.rs"
doctest = false
doc = false
bench = false

[[test]]
name = "tests"
